# Generated by Django 2.0.1 on 2018-01-29 16:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('location', models.CharField(max_length=20)),
                ('url', models.TextField()),
                ('uid', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price', models.CharField(max_length=7)),
                ('created_at', models.DateTimeField()),
                ('deleted_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.TextField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manufacturer', models.CharField(max_length=20)),
                ('model', models.CharField(max_length=20)),
                ('year', models.DateField()),
                ('odometr_value', models.DecimalField(decimal_places=2, max_digits=7)),
                ('deffects', models.BooleanField()),
                ('engine', models.CharField(max_length=30)),
                ('transmission', models.CharField(max_length=20)),
                ('fuel', models.CharField(max_length=20)),
                ('technical_inspection', models.DateField()),
                ('advertisement', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crawler.Advertisement')),
                ('seller', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crawler.Seller')),
            ],
        ),
        migrations.AddField(
            model_name='advertisement',
            name='seller',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crawler.Seller'),
        ),
    ]
