# Generated by Django 2.0.1 on 2018-01-29 17:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='seller',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='crawler.Seller'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='advertisement',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='crawler.Advertisement'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='seller',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='crawler.Seller'),
        ),
    ]
