# Generated by Django 2.0.1 on 2018-01-29 18:25

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0002_auto_20180129_1745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='comment',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2018, 1, 29, 18, 25, 47, 773888, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='deleted_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='price',
            field=models.CharField(blank=True, max_length=7),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='updated_at',
            field=models.DateTimeField(null=True),
        ),
    ]
