# Generated by Django 2.0.1 on 2018-01-30 12:30

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0003_auto_20180129_1825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2018, 1, 30, 12, 30, 11, 338545, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='deffects',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='fuel',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='model',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='odometr_value',
            field=models.DecimalField(decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='technical_inspection',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='transmission',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='year',
            field=models.DateField(null=True),
        ),
    ]
