# Generated by Django 2.0.1 on 2018-02-01 12:28

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0004_auto_20180130_1230'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='manufacturer',
        ),
        migrations.AddField(
            model_name='vehicle',
            name='make',
            field=models.CharField(default=None, max_length=20),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 1, 12, 28, 52, 417636, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='uid',
            field=models.DecimalField(decimal_places=2, max_digits=10, unique=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='model',
            field=models.CharField(default=None, max_length=20),
        ),
    ]
