# Generated by Django 2.0.1 on 2018-02-01 12:58

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0005_auto_20180201_1228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 1, 12, 58, 35, 500017, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='deffects',
            field=models.CharField(max_length=20),
        ),
    ]
