# Generated by Django 2.0.1 on 2018-03-20 16:31

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0009_auto_20180213_1236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 20, 16, 31, 30, 782308, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='deffects',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
