# Generated by Django 2.0.1 on 2018-03-29 15:38

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0010_auto_20180320_1631'),
    ]

    operations = [
        migrations.CreateModel(
            name='CookieStore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('instant', 'Instant'), ('weekly', 'Weekly')], max_length=30, unique=True)),
                ('value', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 29, 15, 38, 45, 691397, tzinfo=utc)),
        ),
    ]
