# Generated by Django 2.0.1 on 2018-03-29 16:23

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0011_auto_20180329_1538'),
    ]

    operations = [
        migrations.AddField(
            model_name='cookiestore',
            name='url',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 29, 16, 23, 0, 962649, tzinfo=utc)),
        ),
    ]
