# Generated by Django 2.0.1 on 2018-03-30 10:14

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0012_auto_20180329_1623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 30, 10, 14, 34, 30032, tzinfo=utc)),
        ),
    ]
