# Generated by Django 2.0.1 on 2018-03-30 14:29

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0013_auto_20180330_1014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 30, 14, 29, 16, 549783, tzinfo=utc)),
        ),
    ]
