# Generated by Django 2.0.1 on 2018-04-01 15:40

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0014_auto_20180330_1429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2018, 4, 1, 15, 40, 48, 575684, tzinfo=utc)),
        ),
    ]
