# Generated by Django 2.0.1 on 2018-04-21 14:15

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0016_auto_20180421_1413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2018, 4, 21, 14, 15, 30, 788065, tzinfo=utc)),
        ),
    ]
