# Generated by Django 2.0.1 on 2018-11-30 15:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0018_auto_20180603_0823'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('continent', models.CharField(max_length=250, null=True)),
                ('state', models.CharField(max_length=250, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SearchCriteria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make', models.CharField(max_length=100, null=True)),
                ('model', models.CharField(max_length=100, null=True)),
                ('year_from', models.DateField(null=True)),
                ('year_to', models.DateField(null=True)),
                ('city', models.CharField(choices=[('Vilnius', 'Vilnius'), ('Kaunas', 'Kaunas')], max_length=100, null=True)),
                ('subscriber', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='crawler.Subscriber')),
            ],
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='location',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='uid',
            field=models.DecimalField(decimal_places=2, max_digits=20, unique=True),
        ),
    ]
