# Generated by Django 2.0.1 on 2018-06-17 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0018_auto_20180603_0823'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebDriverSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('browser', models.CharField(max_length=30)),
                ('uid', models.TextField()),
            ],
        ),
    ]
