# Generated by Django 2.0.1 on 2018-11-30 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0019_auto_20181130_1524'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Country',
        ),
    ]
