# Generated by Django 2.0.1 on 2018-09-08 14:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0019_webdriversession'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchSessions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('portal', models.CharField(choices=[('autoplius', 'Autoplius')], max_length=30)),
                ('search', models.CharField(choices=[('instant', 'Instant'), ('weekly', 'Weekly')], max_length=30)),
                ('url', models.TextField()),
                ('web_dr_session', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='crawler.WebDriverSession')),
            ],
        ),
    ]
