# Generated by Django 2.0.1 on 2018-12-11 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0020_delete_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchcriteria',
            name='enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='searchcriteria',
            name='fuel',
            field=models.CharField(choices=[('Benzinas', 'Benzinas'), ('Dyzelinas', 'Dyzelinas')], max_length=100, null=True),
        ),
    ]
