# Generated by Django 2.0.1 on 2018-11-16 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0020_searchsessions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='searchsessions',
            name='web_dr_session',
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='location',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='uid',
            field=models.DecimalField(decimal_places=2, max_digits=20, unique=True),
        ),
        migrations.DeleteModel(
            name='SearchSessions',
        ),
    ]
