# Generated by Django 2.0.1 on 2019-01-02 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0025_auto_20190102_1305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searchcriteria',
            name='make',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='searchcriteria',
            name='model',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
