# Generated by Django 2.0.1 on 2019-01-04 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0026_auto_20190102_1448'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebDriverSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('browser', models.CharField(max_length=30)),
                ('uid', models.TextField()),
            ],
        ),
    ]
